//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9172
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Tools.Measurement {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Tools.Measurement.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibrate.
        /// </summary>
        public static string CalibrationDialogTitle {
            get {
                return ResourceManager.GetString("CalibrationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Elliptical ROI.
        /// </summary>
        public static string CommandCreateEllipiticalRoi {
            get {
                return ResourceManager.GetString("CommandCreateEllipiticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Polygonal ROI.
        /// </summary>
        public static string CommandCreatePolygonalRoi {
            get {
                return ResourceManager.GetString("CommandCreatePolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Protractor.
        /// </summary>
        public static string CommandCreateProtractor {
            get {
                return ResourceManager.GetString("CommandCreateProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Rectangle ROI.
        /// </summary>
        public static string CommandCreateRectangleRoi {
            get {
                return ResourceManager.GetString("CommandCreateRectangleRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Ruler.
        /// </summary>
        public static string CommandCreateRuler {
            get {
                return ResourceManager.GetString("CommandCreateRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot calibrate a ruler of zero-length..
        /// </summary>
        public static string ErrorCannotCalibrateZeroLengthRuler {
            get {
                return ResourceManager.GetString("ErrorCannotCalibrateZeroLengthRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ellipse {0}.
        /// </summary>
        public static string FormatEllipseName {
            get {
                return ResourceManager.GetString("FormatEllipseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Polygon {0}.
        /// </summary>
        public static string FormatPolygonName {
            get {
                return ResourceManager.GetString("FormatPolygonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protractor {0}.
        /// </summary>
        public static string FormatProtractorName {
            get {
                return ResourceManager.GetString("FormatProtractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rectangle {0}.
        /// </summary>
        public static string FormatRectangleName {
            get {
                return ResourceManager.GetString("FormatRectangleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ruler {0}.
        /// </summary>
        public static string FormatRulerName {
            get {
                return ResourceManager.GetString("FormatRulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibrate.
        /// </summary>
        public static string MenuCalibrationTool {
            get {
                return ResourceManager.GetString("MenuCalibrationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Elliptical ROI.
        /// </summary>
        public static string MenuEllipticalRoi {
            get {
                return ResourceManager.GetString("MenuEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measurement.
        /// </summary>
        public static string MenuMeasurement {
            get {
                return ResourceManager.GetString("MenuMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Polygonal ROI.
        /// </summary>
        public static string MenuPolygonalRoi {
            get {
                return ResourceManager.GetString("MenuPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protractor.
        /// </summary>
        public static string MenuProtractor {
            get {
                return ResourceManager.GetString("MenuProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rectangular ROI.
        /// </summary>
        public static string MenuRectangularRoi {
            get {
                return ResourceManager.GetString("MenuRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ruler.
        /// </summary>
        public static string MenuRuler {
            get {
                return ResourceManager.GetString("MenuRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Angles.
        /// </summary>
        public static string MenuShowAngles {
            get {
                return ResourceManager.GetString("MenuShowAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length must be greater than 0 cm..
        /// </summary>
        public static string MessageInvalidLength {
            get {
                return ResourceManager.GetString("MessageInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N/A.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Elliptical ROI.
        /// </summary>
        public static string ToolbarEllipticalRoi {
            get {
                return ResourceManager.GetString("ToolbarEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Polygonal ROI.
        /// </summary>
        public static string ToolbarPolygonalRoi {
            get {
                return ResourceManager.GetString("ToolbarPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protractor.
        /// </summary>
        public static string ToolbarProtractor {
            get {
                return ResourceManager.GetString("ToolbarProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rectangular ROI.
        /// </summary>
        public static string ToolbarRectangularRoi {
            get {
                return ResourceManager.GetString("ToolbarRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ruler.
        /// </summary>
        public static string ToolbarRuler {
            get {
                return ResourceManager.GetString("ToolbarRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Angles.
        /// </summary>
        public static string ToolbarShowAngles {
            get {
                return ResourceManager.GetString("ToolbarShowAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:F1}°.
        /// </summary>
        public static string ToolsMeasurementFormatDegrees {
            get {
                return ResourceManager.GetString("ToolsMeasurementFormatDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibrate.
        /// </summary>
        public static string TooltipCalibrationTool {
            get {
                return ResourceManager.GetString("TooltipCalibrationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Elliptical ROI.
        /// </summary>
        public static string TooltipEllipticalRoi {
            get {
                return ResourceManager.GetString("TooltipEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Polygonal ROI.
        /// </summary>
        public static string TooltipPolygonalRoi {
            get {
                return ResourceManager.GetString("TooltipPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protractor.
        /// </summary>
        public static string TooltipProtractor {
            get {
                return ResourceManager.GetString("TooltipProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rectangular ROI.
        /// </summary>
        public static string TooltipRectangularRoi {
            get {
                return ResourceManager.GetString("TooltipRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ruler.
        /// </summary>
        public static string TooltipRuler {
            get {
                return ResourceManager.GetString("TooltipRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Angles.
        /// </summary>
        public static string TooltipShowAngles {
            get {
                return ResourceManager.GetString("TooltipShowAngles", resourceCulture);
            }
        }
    }
}
