//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9172
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Volume.Mpr {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Volume.Mpr.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move MPR.
        /// </summary>
        public static string CommandMprMove {
            get {
                return ResourceManager.GetString("CommandMprMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset MPR.
        /// </summary>
        public static string CommandMprReset {
            get {
                return ResourceManager.GetString("CommandMprReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reslice MPR.
        /// </summary>
        public static string CommandMprReslice {
            get {
                return ResourceManager.GetString("CommandMprReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to load the selected images in MPR.
        /// </summary>
        public static string ExceptionMprLoadFailure {
            get {
                return ResourceManager.GetString("ExceptionMprLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MPR ({0}).
        /// </summary>
        public static string FormatMprDisplaySetName {
            get {
                return ResourceManager.GetString("FormatMprDisplaySetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MPR {0}.
        /// </summary>
        public static string FormatMprWorkspaceTitle {
            get {
                return ResourceManager.GetString("FormatMprWorkspaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (X{0:f0}° x Y{1:f0}° x Z{2:f0}°).
        /// </summary>
        public static string FormatSliceCustom {
            get {
                return ResourceManager.GetString("FormatSliceCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Identity.
        /// </summary>
        public static string FormatSliceIdentity {
            get {
                return ResourceManager.GetString("FormatSliceIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OrthoX.
        /// </summary>
        public static string FormatSliceOrthogonalX {
            get {
                return ResourceManager.GetString("FormatSliceOrthogonalX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OrthoY.
        /// </summary>
        public static string FormatSliceOrthogonalY {
            get {
                return ResourceManager.GetString("FormatSliceOrthogonalY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - {1}.
        /// </summary>
        public static string FormatVolumeLabel {
            get {
                return ResourceManager.GetString("FormatVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {2} ({0} - {1}).
        /// </summary>
        public static string FormatVolumeLabelWithSeries {
            get {
                return ResourceManager.GetString("FormatVolumeLabelWithSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Debug.
        /// </summary>
        public static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;MPR.
        /// </summary>
        public static string MenuMpr {
            get {
                return ResourceManager.GetString("MenuMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Selection with &amp;MPR.
        /// </summary>
        public static string MenuOpenSelectionWithMpr {
            get {
                return ResourceManager.GetString("MenuOpenSelectionWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open with &amp;MPR....
        /// </summary>
        public static string MenuOpenWithMpr {
            get {
                return ResourceManager.GetString("MenuOpenWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Reset MPR.
        /// </summary>
        public static string MenuResetAll {
            get {
                return ResourceManager.GetString("MenuResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reslice MPR.
        /// </summary>
        public static string MenuReslice {
            get {
                return ResourceManager.GetString("MenuReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reslice {0}.
        /// </summary>
        public static string MenuResliceFor {
            get {
                return ResourceManager.GetString("MenuResliceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Volume.
        /// </summary>
        public static string MenuVolume {
            get {
                return ResourceManager.GetString("MenuVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Building MPR Volume....
        /// </summary>
        public static string MessageBuildingMprVolume {
            get {
                return ResourceManager.GetString("MessageBuildingMprVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Building MPR Volume (Frame {1} of {2})....
        /// </summary>
        public static string MessageBuildingMprVolumeProgress {
            get {
                return ResourceManager.GetString("MessageBuildingMprVolumeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done!.
        /// </summary>
        public static string MessageDone {
            get {
                return ResourceManager.GetString("MessageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing MPR....
        /// </summary>
        public static string MessageInitializingMpr {
            get {
                return ResourceManager.GetString("MessageInitializingMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Performing MPR Workspace Layout....
        /// </summary>
        public static string MessagePerformingMprWorkspaceLayout {
            get {
                return ResourceManager.GetString("MessagePerformingMprWorkspaceLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is not a valid, supported DICOM image SOP instance. {0}.
        /// </summary>
        public static string MessageUnsupportedDicomImageSop {
            get {
                return ResourceManager.GetString("MessageUnsupportedDicomImageSop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slice spacing must be greater than or equal to 0.5 and less than or equal to 10..
        /// </summary>
        public static string MessageValidateSliceSpacing {
            get {
                return ResourceManager.GetString("MessageValidateSliceSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MPR.
        /// </summary>
        public static string Mpr {
            get {
                return ResourceManager.GetString("Mpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 Plane.
        /// </summary>
        public static string ThreePlane {
            get {
                return ResourceManager.GetString("ThreePlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MPR.
        /// </summary>
        public static string ToolbarMpr {
            get {
                return ResourceManager.GetString("ToolbarMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Selection with MPR.
        /// </summary>
        public static string ToolbarOpenSelectionWithMpr {
            get {
                return ResourceManager.GetString("ToolbarOpenSelectionWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset MPR.
        /// </summary>
        public static string ToolbarResetAll {
            get {
                return ResourceManager.GetString("ToolbarResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reslice MPR.
        /// </summary>
        public static string ToolbarReslice {
            get {
                return ResourceManager.GetString("ToolbarReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reslice {0}.
        /// </summary>
        public static string ToolbarResliceFor {
            get {
                return ResourceManager.GetString("ToolbarResliceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resets all MPR slice views.
        /// </summary>
        public static string TooltipResetAll {
            get {
                return ResourceManager.GetString("TooltipResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ::.
        /// </summary>
        public static string VolumeLabelSeparator {
            get {
                return ResourceManager.GetString("VolumeLabelSeparator", resourceCulture);
            }
        }
    }
}
