//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9172
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.StudyFinders.Remote {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.StudyFinders.Remote.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple wildcard queries cannot be performed on the ModalitiesInStudy tag..
        /// </summary>
        public static string ExceptionModalitiesInStudyCannotPerformMultipleWildcardQueries {
            get {
                return ResourceManager.GetString("ExceptionModalitiesInStudyCannotPerformMultipleWildcardQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Association rejected ({0})..
        /// </summary>
        public static string MessageFormatAssociationRejected {
            get {
                return ResourceManager.GetString("MessageFormatAssociationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection failed ({0})..
        /// </summary>
        public static string MessageFormatConnectionFailed {
            get {
                return ResourceManager.GetString("MessageFormatConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The connection timeout expired ({0})..
        /// </summary>
        public static string MessageFormatConnectTimeoutExpired {
            get {
                return ResourceManager.GetString("MessageFormatConnectTimeoutExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The query operation failed ({0})..
        /// </summary>
        public static string MessageFormatQueryOperationFailed {
            get {
                return ResourceManager.GetString("MessageFormatQueryOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The remote server cancelled the query ({0})..
        /// </summary>
        public static string MessageFormatRemoteServerCancelledFind {
            get {
                return ResourceManager.GetString("MessageFormatRemoteServerCancelledFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unexpected message was received; aborted association..
        /// </summary>
        public static string MessageUnexpectedMessage {
            get {
                return ResourceManager.GetString("MessageUnexpectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unexpected network error has occurred..
        /// </summary>
        public static string MessageUnexpectedNetworkError {
            get {
                return ResourceManager.GetString("MessageUnexpectedNetworkError", resourceCulture);
            }
        }
    }
}
