//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9172
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Desktop.ExtensionBrowser {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Desktop.ExtensionBrowser.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension Points ({0}).
        /// </summary>
        public static string FormatExtensionPointsDisplayName {
            get {
                return ResourceManager.GetString("FormatExtensionPointsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension Browser.
        /// </summary>
        public static string MenuExtensionBrowser {
            get {
                return ResourceManager.GetString("MenuExtensionBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension Browser.
        /// </summary>
        public static string TitleExtensionBrowser {
            get {
                return ResourceManager.GetString("TitleExtensionBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extensions ({0}).
        /// </summary>
        public static string TreeExtensionPointViewExtensionsNode {
            get {
                return ResourceManager.GetString("TreeExtensionPointViewExtensionsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension Points ({0}).
        /// </summary>
        public static string TreeExtensionPointViewRootNode {
            get {
                return ResourceManager.GetString("TreeExtensionPointViewRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension Points ({0}).
        /// </summary>
        public static string TreePluginViewExtensionPointsNode {
            get {
                return ResourceManager.GetString("TreePluginViewExtensionPointsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension Points declared in plugin {0}.
        /// </summary>
        public static string TreePluginViewExtensionPointsNodeDetails {
            get {
                return ResourceManager.GetString("TreePluginViewExtensionPointsNodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extensions ({0}).
        /// </summary>
        public static string TreePluginViewExtensionsNode {
            get {
                return ResourceManager.GetString("TreePluginViewExtensionsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extensions declared in plugin {0}.
        /// </summary>
        public static string TreePluginViewExtensionsNodeDetails {
            get {
                return ResourceManager.GetString("TreePluginViewExtensionsNodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plugins ({0}).
        /// </summary>
        public static string TreePluginViewRootNode {
            get {
                return ResourceManager.GetString("TreePluginViewRootNode", resourceCulture);
            }
        }
    }
}
