//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9172
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Dicom {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Dicom.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non-DICOM, application-level logic exception or execution failure.
        /// </summary>
        public static string ExceptionApplicationLevelLogic {
            get {
                return ResourceManager.GetString("ExceptionApplicationLevelLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The AE Title cannot be null.
        /// </summary>
        public static string ExceptionDicomAETitleNull {
            get {
                return ResourceManager.GetString("ExceptionDicomAETitleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The AE Title cannot be zero-length.
        /// </summary>
        public static string ExceptionDicomAETitleZeroLength {
            get {
                return ResourceManager.GetString("ExceptionDicomAETitleZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The connection timeout value must be between 1 and 32767.
        /// </summary>
        public static string ExceptionDicomConnectionTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionDicomConnectionTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File: {0} - {1}.
        /// </summary>
        public static string ExceptionDICOMFile {
            get {
                return ResourceManager.GetString("ExceptionDICOMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The find dataset cannot be null.
        /// </summary>
        public static string ExceptionDicomFindDatasetNull {
            get {
                return ResourceManager.GetString("ExceptionDicomFindDatasetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The hostname cannot be null.
        /// </summary>
        public static string ExceptionDicomHostnameNull {
            get {
                return ResourceManager.GetString("ExceptionDicomHostnameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The hostname cannot be zero-length.
        /// </summary>
        public static string ExceptionDicomHostnameZeroLength {
            get {
                return ResourceManager.GetString("ExceptionDicomHostnameZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The listeningPort must be greater than zero and less than System.Int32.MaxValue.
        /// </summary>
        public static string ExceptionDicomListeningPortOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionDicomListeningPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The move dataset cannot be null.
        /// </summary>
        public static string ExceptionDicomMoveDatasetNull {
            get {
                return ResourceManager.GetString("ExceptionDicomMoveDatasetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The passed in dataset is null.
        /// </summary>
        public static string ExceptionDicomNullDataset {
            get {
                return ResourceManager.GetString("ExceptionDicomNullDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PATIENT level query using the Study Root Query/Retrieve Information model is invalid.
        /// </summary>
        public static string ExceptionDicomPatientLevelQueryInvalid {
            get {
                return ResourceManager.GetString("ExceptionDicomPatientLevelQueryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified directory where incoming DICOM objects should be saved does not exist - {0}.
        /// </summary>
        public static string ExceptionDicomSaveDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionDicomSaveDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The directory where inbound DICOM objects are stored cannot be null.
        /// </summary>
        public static string ExceptionDicomSaveDirectoryNull {
            get {
                return ResourceManager.GetString("ExceptionDicomSaveDirectoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag: {0} - {1}.
        /// </summary>
        public static string ExceptionDICOMTag {
            get {
                return ResourceManager.GetString("ExceptionDICOMTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer syntax {0} for SOP UID = {1} not supported.  Compressed pixel data cannot be loaded at this time..
        /// </summary>
        public static string ExceptionDicomTransferSyntaxNotSupported {
            get {
                return ResourceManager.GetString("ExceptionDicomTransferSyntaxNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Find failed: operation was cancelled..
        /// </summary>
        public static string ExceptionFindCancelled {
            get {
                return ResourceManager.GetString("ExceptionFindCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Find failed: identifier does not match SOP Class..
        /// </summary>
        public static string ExceptionFindFailedIdentifierDoesNotMatchSOPClass {
            get {
                return ResourceManager.GetString("ExceptionFindFailedIdentifierDoesNotMatchSOPClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Find failed: unable to process..
        /// </summary>
        public static string ExceptionFindFailedUnableToProcess {
            get {
                return ResourceManager.GetString("ExceptionFindFailedUnableToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Find warning: unsupported optional keys..
        /// </summary>
        public static string ExceptionFindPendingWarningUnsupportedOptionalKeys {
            get {
                return ResourceManager.GetString("ExceptionFindPendingWarningUnsupportedOptionalKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Find refused: out of resources..
        /// </summary>
        public static string ExceptionFindRefusedOutOfResources {
            get {
                return ResourceManager.GetString("ExceptionFindRefusedOutOfResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Find refused: SOP Class not supported..
        /// </summary>
        public static string ExceptionFindRefusedSOPClassNotSupported {
            get {
                return ResourceManager.GetString("ExceptionFindRefusedSOPClassNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Accession Number cannot be null.
        /// </summary>
        public static string ExceptionGeneralAccessionNull {
            get {
                return ResourceManager.GetString("ExceptionGeneralAccessionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Accession Number cannot be zero-length.
        /// </summary>
        public static string ExceptionGeneralAccessionZeroLength {
            get {
                return ResourceManager.GetString("ExceptionGeneralAccessionZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The object passed is not of the right type for Equals comparison..
        /// </summary>
        public static string ExceptionGeneralEqualsWrongType {
            get {
                return ResourceManager.GetString("ExceptionGeneralEqualsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The argument to CompareTo for the type Uid is not itself of type Uid.
        /// </summary>
        public static string ExceptionGeneralUidCompareToTypeIncorrect {
            get {
                return ResourceManager.GetString("ExceptionGeneralUidCompareToTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid DICOM UID format: {0}.
        /// </summary>
        public static string ExceptionGeneralUIDFormat {
            get {
                return ResourceManager.GetString("ExceptionGeneralUIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UID cannot exceeed 64 characters: {0}.
        /// </summary>
        public static string ExceptionGeneralUIDLength {
            get {
                return ResourceManager.GetString("ExceptionGeneralUIDLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The UID cannot be null.
        /// </summary>
        public static string ExceptionGeneralUidNull {
            get {
                return ResourceManager.GetString("ExceptionGeneralUidNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The UID cannot be zero-length.
        /// </summary>
        public static string ExceptionGeneralUidZeroLength {
            get {
                return ResourceManager.GetString("ExceptionGeneralUidZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BitsAllocated must be either 8 or 16 (bitsAllocated = {0})..
        /// </summary>
        public static string ExceptionInvalidBitsAllocated {
            get {
                return ResourceManager.GetString("ExceptionInvalidBitsAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BitsStored must be greater than zero (bitsStored = {0})..
        /// </summary>
        public static string ExceptionInvalidBitsStored {
            get {
                return ResourceManager.GetString("ExceptionInvalidBitsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BitsStored must be &lt;= BitsAllocated (bitsStored = {0}, bitsAllocated = {1})..
        /// </summary>
        public static string ExceptionInvalidBitsStoredBitsAllocated {
            get {
                return ResourceManager.GetString("ExceptionInvalidBitsStoredBitsAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Columns must be greater than zero (columns = {0})..
        /// </summary>
        public static string ExceptionInvalidColumns {
            get {
                return ResourceManager.GetString("ExceptionInvalidColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid film size: {0}.
        /// </summary>
        public static string ExceptionInvalidFilmSize {
            get {
                return ResourceManager.GetString("ExceptionInvalidFilmSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HighBit must be greater than zero (highBit = {0})..
        /// </summary>
        public static string ExceptionInvalidHighBit {
            get {
                return ResourceManager.GetString("ExceptionInvalidHighBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HighBit must be &lt;= BitsAllocated - 1 (highBit = {0}, bitsAllocated = {1})..
        /// </summary>
        public static string ExceptionInvalidHighBitBitsAllocated {
            get {
                return ResourceManager.GetString("ExceptionInvalidHighBitBitsAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid image display format: {0}.
        /// </summary>
        public static string ExceptionInvalidImageDisplayFormat {
            get {
                return ResourceManager.GetString("ExceptionInvalidImageDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PhotometricInterpretation must be one of the enumerated values specified in DICOM PS 3.3 (photometricInterpretation = {0})..
        /// </summary>
        public static string ExceptionInvalidPhotometricInterpretation {
            get {
                return ResourceManager.GetString("ExceptionInvalidPhotometricInterpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PhotometricInterpretation must be consistent with the the number of SamplesPerPixel (photometricInterpretation = {0}, samplesPerPixel = {1})..
        /// </summary>
        public static string ExceptionInvalidPhotometricInterpretationSamplesPerPixel {
            get {
                return ResourceManager.GetString("ExceptionInvalidPhotometricInterpretationSamplesPerPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PixelData length must be equal to SizeInBytes (pixelDataLength = {0}, sizeInBytes = {1})..
        /// </summary>
        public static string ExceptionInvalidPixelData {
            get {
                return ResourceManager.GetString("ExceptionInvalidPixelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PixelRepresentation must be 0 or 1 (pixelRepresentation = {0})..
        /// </summary>
        public static string ExceptionInvalidPixelRepresentation {
            get {
                return ResourceManager.GetString("ExceptionInvalidPixelRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PlanarConfiguration must be 0 or 1 (planarConfiguration = {0})..
        /// </summary>
        public static string ExceptionInvalidPlanarConfiguration {
            get {
                return ResourceManager.GetString("ExceptionInvalidPlanarConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rows must be greater than zero (rows = {0})..
        /// </summary>
        public static string ExceptionInvalidRows {
            get {
                return ResourceManager.GetString("ExceptionInvalidRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SamplesPerPixel must be 1, 3 or 4 (samplesPerPixel = {0})..
        /// </summary>
        public static string ExceptionInvalidSamplesPerPixel {
            get {
                return ResourceManager.GetString("ExceptionInvalidSamplesPerPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SeriesInstanceUID must not be empty..
        /// </summary>
        public static string ExceptionInvalidSeriesInstanceUID {
            get {
                return ResourceManager.GetString("ExceptionInvalidSeriesInstanceUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SizeInBytes improperly calculated (correct size = {0}, calculated size {1})..
        /// </summary>
        public static string ExceptionInvalidSizeInBytes {
            get {
                return ResourceManager.GetString("ExceptionInvalidSizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SOPInstanceUID must not be empty..
        /// </summary>
        public static string ExceptionInvalidSOPInstanceUID {
            get {
                return ResourceManager.GetString("ExceptionInvalidSOPInstanceUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StudyInstanceUID must not be empty..
        /// </summary>
        public static string ExceptionInvalidStudyInstanceUID {
            get {
                return ResourceManager.GetString("ExceptionInvalidStudyInstanceUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The TransferSyntaxUID cannot be empty..
        /// </summary>
        public static string ExceptionInvalidTransferUID {
            get {
                return ResourceManager.GetString("ExceptionInvalidTransferUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Move failed: operation was cancelled..
        /// </summary>
        public static string ExceptionMoveCancelled {
            get {
                return ResourceManager.GetString("ExceptionMoveCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Move failed: destination unknown..
        /// </summary>
        public static string ExceptionMoveFailedDestinationUnknown {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedDestinationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Move failed: Identifier does not match SOP Class..
        /// </summary>
        public static string ExceptionMoveFailedIdentifierDoesNotMatchSOPClass {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedIdentifierDoesNotMatchSOPClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Move failed: out of resources (number of matches)..
        /// </summary>
        public static string ExceptionMoveFailedOutOfResourcesNumberOfMatches {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedOutOfResourcesNumberOfMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Move failed: out of resources (sub-operations)..
        /// </summary>
        public static string ExceptionMoveFailedOutOfResourcesSubOperations {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedOutOfResourcesSubOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Move failed: SOP Class not supported..
        /// </summary>
        public static string ExceptionMoveFailedSopClassNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedSopClassNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Move failed: unable to process..
        /// </summary>
        public static string ExceptionMoveFailedUnableToProcess {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedUnableToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C-Move warning: sub-operations completed; one or more failures..
        /// </summary>
        public static string ExceptionMoveWarningSuboperationsCompleteOneOrMoreFailures {
            get {
                return ResourceManager.GetString("ExceptionMoveWarningSuboperationsCompleteOneOrMoreFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image display format {0} is not supported..
        /// </summary>
        public static string ExceptionNotSupportedImageDisplayFormat {
            get {
                return ResourceManager.GetString("ExceptionNotSupportedImageDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is null.
        /// </summary>
        public static string ExceptionNullReference {
            get {
                return ResourceManager.GetString("ExceptionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Poorly formatted DICOM date range {0}..
        /// </summary>
        public static string ExceptionPoorlyFormattedDateRange {
            get {
                return ResourceManager.GetString("ExceptionPoorlyFormattedDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sequence queries are not supported at this time (tag path = {0})..
        /// </summary>
        public static string ExceptionSequenceQueriesNotSupported {
            get {
                return ResourceManager.GetString("ExceptionSequenceQueriesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} ({1}).
        /// </summary>
        public static string FormatCodeSequenceValue {
            get {
                return ResourceManager.GetString("FormatCodeSequenceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} {2} x {1} {2}.
        /// </summary>
        public static string FormatFilmSize {
            get {
                return ResourceManager.GetString("FormatFilmSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column {0}.
        /// </summary>
        public static string FormatImageDisplayFormatColumn {
            get {
                return ResourceManager.GetString("FormatImageDisplayFormatColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Row {0}.
        /// </summary>
        public static string FormatImageDisplayFormatRow {
            get {
                return ResourceManager.GetString("FormatImageDisplayFormatRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard {0}x{1}.
        /// </summary>
        public static string FormatImageDisplayFormatStandard {
            get {
                return ResourceManager.GetString("FormatImageDisplayFormatStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type being set is not compatible with the value representation of the tag..
        /// </summary>
        public static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Value Representatoin (VR)  selected was invalid for the tag..
        /// </summary>
        public static string InvalidVR {
            get {
                return ResourceManager.GetString("InvalidVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Black.
        /// </summary>
        public static string LabelFilmDensityBlack {
            get {
                return ResourceManager.GetString("LabelFilmDensityBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на White.
        /// </summary>
        public static string LabelFilmDensityWhite {
            get {
                return ResourceManager.GetString("LabelFilmDensityWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bin {0}.
        /// </summary>
        public static string LabelFilmDestinationBinN {
            get {
                return ResourceManager.GetString("LabelFilmDestinationBinN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Magazine.
        /// </summary>
        public static string LabelFilmDestinationMagazine {
            get {
                return ResourceManager.GetString("LabelFilmDestinationMagazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processor.
        /// </summary>
        public static string LabelFilmDestinationProcessor {
            get {
                return ResourceManager.GetString("LabelFilmDestinationProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bilinear.
        /// </summary>
        public static string LabelFilmMagnificationTypeBilinear {
            get {
                return ResourceManager.GetString("LabelFilmMagnificationTypeBilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cubic.
        /// </summary>
        public static string LabelFilmMagnificationTypeCubic {
            get {
                return ResourceManager.GetString("LabelFilmMagnificationTypeCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replicate.
        /// </summary>
        public static string LabelFilmMagnificationTypeReplicate {
            get {
                return ResourceManager.GetString("LabelFilmMagnificationTypeReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blue Film.
        /// </summary>
        public static string LabelFilmMediumTypeBlueFilm {
            get {
                return ResourceManager.GetString("LabelFilmMediumTypeBlueFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear Film.
        /// </summary>
        public static string LabelFilmMediumTypeClearFilm {
            get {
                return ResourceManager.GetString("LabelFilmMediumTypeClearFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mammo Blue Film.
        /// </summary>
        public static string LabelFilmMediumTypeMammoBlueFilm {
            get {
                return ResourceManager.GetString("LabelFilmMediumTypeMammoBlueFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mammo Clear Film.
        /// </summary>
        public static string LabelFilmMediumTypeMammoClearFilm {
            get {
                return ResourceManager.GetString("LabelFilmMediumTypeMammoClearFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paper.
        /// </summary>
        public static string LabelFilmMediumTypePaper {
            get {
                return ResourceManager.GetString("LabelFilmMediumTypePaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Landscape.
        /// </summary>
        public static string LabelFilmOrientationLandscape {
            get {
                return ResourceManager.GetString("LabelFilmOrientationLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Portrait.
        /// </summary>
        public static string LabelFilmOrientationPortrait {
            get {
                return ResourceManager.GetString("LabelFilmOrientationPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High.
        /// </summary>
        public static string LabelFilmRequestedResolutionHigh {
            get {
                return ResourceManager.GetString("LabelFilmRequestedResolutionHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard.
        /// </summary>
        public static string LabelFilmRequestedResolutionStandard {
            get {
                return ResourceManager.GetString("LabelFilmRequestedResolutionStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cm.
        /// </summary>
        public static string LabelFilmSizeUnitCentimeter {
            get {
                return ResourceManager.GetString("LabelFilmSizeUnitCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на in.
        /// </summary>
        public static string LabelFilmSizeUnitInch {
            get {
                return ResourceManager.GetString("LabelFilmSizeUnitInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cubic.
        /// </summary>
        public static string LabelFilmSmoothingTypeCubic {
            get {
                return ResourceManager.GetString("LabelFilmSmoothingTypeCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Anterior.
        /// </summary>
        public static string LabelPatientDirectionAnterior {
            get {
                return ResourceManager.GetString("LabelPatientDirectionAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Caudal.
        /// </summary>
        public static string LabelPatientDirectionCaudal {
            get {
                return ResourceManager.GetString("LabelPatientDirectionCaudal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cranial.
        /// </summary>
        public static string LabelPatientDirectionCranial {
            get {
                return ResourceManager.GetString("LabelPatientDirectionCranial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distal.
        /// </summary>
        public static string LabelPatientDirectionDistal {
            get {
                return ResourceManager.GetString("LabelPatientDirectionDistal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dorsal.
        /// </summary>
        public static string LabelPatientDirectionDorsal {
            get {
                return ResourceManager.GetString("LabelPatientDirectionDorsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Foot.
        /// </summary>
        public static string LabelPatientDirectionFoot {
            get {
                return ResourceManager.GetString("LabelPatientDirectionFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Head.
        /// </summary>
        public static string LabelPatientDirectionHead {
            get {
                return ResourceManager.GetString("LabelPatientDirectionHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lateral.
        /// </summary>
        public static string LabelPatientDirectionLateral {
            get {
                return ResourceManager.GetString("LabelPatientDirectionLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left.
        /// </summary>
        public static string LabelPatientDirectionLeft {
            get {
                return ResourceManager.GetString("LabelPatientDirectionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medial.
        /// </summary>
        public static string LabelPatientDirectionMedial {
            get {
                return ResourceManager.GetString("LabelPatientDirectionMedial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Palmar.
        /// </summary>
        public static string LabelPatientDirectionPalmar {
            get {
                return ResourceManager.GetString("LabelPatientDirectionPalmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plantar.
        /// </summary>
        public static string LabelPatientDirectionPlantar {
            get {
                return ResourceManager.GetString("LabelPatientDirectionPlantar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Posterior.
        /// </summary>
        public static string LabelPatientDirectionPosterior {
            get {
                return ResourceManager.GetString("LabelPatientDirectionPosterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proximal.
        /// </summary>
        public static string LabelPatientDirectionProximal {
            get {
                return ResourceManager.GetString("LabelPatientDirectionProximal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right.
        /// </summary>
        public static string LabelPatientDirectionRight {
            get {
                return ResourceManager.GetString("LabelPatientDirectionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rostral.
        /// </summary>
        public static string LabelPatientDirectionRostral {
            get {
                return ResourceManager.GetString("LabelPatientDirectionRostral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -.
        /// </summary>
        public static string LabelPatientDirectionSeparator {
            get {
                return ResourceManager.GetString("LabelPatientDirectionSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unspecified.
        /// </summary>
        public static string LabelPatientDirectionUnspecified {
            get {
                return ResourceManager.GetString("LabelPatientDirectionUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ventral.
        /// </summary>
        public static string LabelPatientDirectionVentral {
            get {
                return ResourceManager.GetString("LabelPatientDirectionVentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High.
        /// </summary>
        public static string LabelPrintPriorityHigh {
            get {
                return ResourceManager.GetString("LabelPrintPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low.
        /// </summary>
        public static string LabelPrintPriorityLow {
            get {
                return ResourceManager.GetString("LabelPrintPriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium.
        /// </summary>
        public static string LabelPrintPriorityMedium {
            get {
                return ResourceManager.GetString("LabelPrintPriorityMedium", resourceCulture);
            }
        }
    }
}
