//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9172
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Desktop {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Desktop.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string AlertFilterAll {
            get {
                return ResourceManager.GetString("AlertFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Errors and Warnings.
        /// </summary>
        public static string AlertFilterErrorsAndWarnings {
            get {
                return ResourceManager.GetString("AlertFilterErrorsAndWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Errors only.
        /// </summary>
        public static string AlertFilterErrorsOnly {
            get {
                return ResourceManager.GetString("AlertFilterErrorsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        public static string ColumnLevel {
            get {
                return ResourceManager.GetString("ColumnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        public static string ColumnMessage {
            get {
                return ResourceManager.GetString("ColumnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string ColumnTime {
            get {
                return ResourceManager.GetString("ColumnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workspace.
        /// </summary>
        public static string ColumnWorkspace {
            get {
                return ResourceManager.GetString("ColumnWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default Theme.
        /// </summary>
        public static string DescriptionDefaultTheme {
            get {
                return ResourceManager.GetString("DescriptionDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configures global exception handling behaviour..
        /// </summary>
        public static string DescriptionExceptionHandlerSettings {
            get {
                return ResourceManager.GetString("DescriptionExceptionHandlerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows configuration of display format of common items such as dates, times, etc..
        /// </summary>
        public static string DescriptionFormatSettings {
            get {
                return ResourceManager.GetString("DescriptionFormatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The event {0} does not exist for class {1}..
        /// </summary>
        public static string ExceptionActionBuilderEventDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderEventDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The method {0} does not exist for class {1}, or it does not have the correct signature..
        /// </summary>
        public static string ExceptionActionBuilderMethodDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderMethodDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The property {0} does not exist for class {1}, or it does not have the correct return type..
        /// </summary>
        public static string ExceptionActionBuilderPropertyDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderPropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The property {0} on class {1} does not have a public get method..
        /// </summary>
        public static string ExceptionActionBuilderPropertyDoesNotHavePublicGetMethod {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderPropertyDoesNotHavePublicGetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set the active workspace to null..
        /// </summary>
        public static string ExceptionActiveWorkspaceCannotBeNull {
            get {
                return ResourceManager.GetString("ExceptionActiveWorkspaceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An AssociateViewAttribute must be specified for the input Type in order to create the Associated View..
        /// </summary>
        public static string ExceptionAssociateViewAttributeNotSpecified {
            get {
                return ResourceManager.GetString("ExceptionAssociateViewAttributeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot load exception dialog settings - defaulting to detailed view.
        /// </summary>
        public static string ExceptionCannotLoadExceptionDialogSetting {
            get {
                return ResourceManager.GetString("ExceptionCannotLoadExceptionDialogSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set pane after container has been started..
        /// </summary>
        public static string ExceptionCannotSetPaneAfterContainerStarted {
            get {
                return ResourceManager.GetString("ExceptionCannotSetPaneAfterContainerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Component has already been started..
        /// </summary>
        public static string ExceptionComponentAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionComponentAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Component was never started, or has already been stopped..
        /// </summary>
        public static string ExceptionComponentNeverStarted {
            get {
                return ResourceManager.GetString("ExceptionComponentNeverStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container has already been started.
        /// </summary>
        public static string ExceptionContainerAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionContainerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container was never started, or has already been stopped..
        /// </summary>
        public static string ExceptionContainerNeverStarted {
            get {
                return ResourceManager.GetString("ExceptionContainerNeverStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The main desktop view has not been created..
        /// </summary>
        public static string ExceptionDesktopViewNotCreated {
            get {
                return ResourceManager.GetString("ExceptionDesktopViewNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured while attempting to save changes to this item.
        /// </summary>
        public static string ExceptionFailedToSave {
            get {
                return ResourceManager.GetString("ExceptionFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid action path.  Path must have 2 or more segments..
        /// </summary>
        public static string ExceptionInvalidActionPath {
            get {
                return ResourceManager.GetString("ExceptionInvalidActionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection already contains this object.
        /// </summary>
        public static string ExceptionObjectAlreadyInCollection {
            get {
                return ResourceManager.GetString("ExceptionObjectAlreadyInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An object with the name {0} already exists.
        /// </summary>
        public static string ExceptionObjectWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionObjectWithNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reference property must be of same type as validating property..
        /// </summary>
        public static string ExceptionReferencePropertyMustBeOfSameType {
            get {
                return ResourceManager.GetString("ExceptionReferencePropertyMustBeOfSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reference value must be of same type as validating property..
        /// </summary>
        public static string ExceptionReferenceValueMustBeOfSameType {
            get {
                return ResourceManager.GetString("ExceptionReferenceValueMustBeOfSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Component cannot exit because it is not at the top of the component stack..
        /// </summary>
        public static string ExceptionStackComponentCannotExit {
            get {
                return ResourceManager.GetString("ExceptionStackComponentCannotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot pop - component stack is empty..
        /// </summary>
        public static string ExceptionStackComponentCannotPop {
            get {
                return ResourceManager.GetString("ExceptionStackComponentCannotPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This column must be added to a table to determine its percentage width..
        /// </summary>
        public static string ExceptionTableColumnMustBeAddedToDetermineWidth {
            get {
                return ResourceManager.GetString("ExceptionTableColumnMustBeAddedToDetermineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table item not found in collection..
        /// </summary>
        public static string ExceptionTableItemNotFoundInCollection {
            get {
                return ResourceManager.GetString("ExceptionTableItemNotFoundInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application configuration upgrades are performed by the LocalFileSettingsProvider included in the .NET framework..
        /// </summary>
        public static string ExceptionUpgradeNotSupported {
            get {
                return ResourceManager.GetString("ExceptionUpgradeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} attribute cannot be applied to property of type {1}..
        /// </summary>
        public static string FormatAttributeCannotBeAppliedToPropertyType {
            get {
                return ResourceManager.GetString("FormatAttributeCannotBeAppliedToPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} days from now.
        /// </summary>
        public static string FormatDateInFutureDays {
            get {
                return ResourceManager.GetString("FormatDateInFutureDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} days ago.
        /// </summary>
        public static string FormatDateInPastDays {
            get {
                return ResourceManager.GetString("FormatDateInPastDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} [{1}].
        /// </summary>
        public static string FormatDesktopWindowTitle {
            get {
                return ResourceManager.GetString("FormatDesktopWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More than {0} characters required.
        /// </summary>
        public static string FormatMoreThanXCharactersRequired {
            get {
                return ResourceManager.GetString("FormatMoreThanXCharactersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must be greater than {0}.
        /// </summary>
        public static string FormatMustBeGreaterThan {
            get {
                return ResourceManager.GetString("FormatMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must be greater than or equal to {0}.
        /// </summary>
        public static string FormatMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FormatMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must be less than {0}.
        /// </summary>
        public static string FormatMustBeLessThan {
            get {
                return ResourceManager.GetString("FormatMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must be less than or equal to {0}.
        /// </summary>
        public static string FormatMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FormatMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Between {0} and {1} characters required.
        /// </summary>
        public static string FormatRangeCharactersRequired {
            get {
                return ResourceManager.GetString("FormatRangeCharactersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today {0}.
        /// </summary>
        public static string FormatTimeToday {
            get {
                return ResourceManager.GetString("FormatTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tomorrow {0}.
        /// </summary>
        public static string FormatTimeTomorrow {
            get {
                return ResourceManager.GetString("FormatTimeTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yesterday {0}.
        /// </summary>
        public static string FormatTimeYesterday {
            get {
                return ResourceManager.GetString("FormatTimeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Evaluated For {0} Days.
        /// </summary>
        public static string FormatTotalDaysUsed {
            get {
                return ResourceManager.GetString("FormatTotalDaysUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The custom date format must be from the available list..
        /// </summary>
        public static string InvalidCustomDateFormat {
            get {
                return ResourceManager.GetString("InvalidCustomDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Actions.
        /// </summary>
        public static string LabelAllActions {
            get {
                return ResourceManager.GetString("LabelAllActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colour.
        /// </summary>
        public static string LabelColor {
            get {
                return ResourceManager.GetString("LabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Offline) Values shown may not be accurate, and changes may not be saved..
        /// </summary>
        public static string LabelConfigurationWarningOffline {
            get {
                return ResourceManager.GetString("LabelConfigurationWarningOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Evaluation.
        /// </summary>
        public static string LabelEvaluation {
            get {
                return ResourceManager.GetString("LabelEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Evaluation ({0} days).
        /// </summary>
        public static string LabelEvaluationWithDays {
            get {
                return ResourceManager.GetString("LabelEvaluationWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        public static string LabelImport {
            get {
                return ResourceManager.GetString("LabelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Large.
        /// </summary>
        public static string LabelLarge {
            get {
                return ResourceManager.GetString("LabelLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium.
        /// </summary>
        public static string LabelMedium {
            get {
                return ResourceManager.GetString("LabelMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monochrome.
        /// </summary>
        public static string LabelMonochrome {
            get {
                return ResourceManager.GetString("LabelMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Group.
        /// </summary>
        public static string LabelNewGroup {
            get {
                return ResourceManager.GetString("LabelNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not for Diagnostic Use.
        /// </summary>
        public static string LabelNotForDiagnosticUse {
            get {
                return ResourceManager.GetString("LabelNotForDiagnosticUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not for Human Diagnosis.
        /// </summary>
        public static string LabelNotForHumanDiagnosis {
            get {
                return ResourceManager.GetString("LabelNotForHumanDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string LabelReset {
            get {
                return ResourceManager.GetString("LabelReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset All.
        /// </summary>
        public static string LabelResetAll {
            get {
                return ResourceManager.GetString("LabelResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save All.
        /// </summary>
        public static string LabelSaveAll {
            get {
                return ResourceManager.GetString("LabelSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Separator).
        /// </summary>
        public static string LabelSeparator {
            get {
                return ResourceManager.GetString("LabelSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small.
        /// </summary>
        public static string LabelSmall {
            get {
                return ResourceManager.GetString("LabelSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin.
        /// </summary>
        public static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alerts.
        /// </summary>
        public static string MenuAlertViewer {
            get {
                return ResourceManager.GetString("MenuAlertViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string MenuCloseWindow {
            get {
                return ResourceManager.GetString("MenuCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close Workspace.
        /// </summary>
        public static string MenuCloseWorkspace {
            get {
                return ResourceManager.GetString("MenuCloseWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings Editor.
        /// </summary>
        public static string MenuConfigureSettings {
            get {
                return ResourceManager.GetString("MenuConfigureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contents.
        /// </summary>
        public static string MenuContents {
            get {
                return ResourceManager.GetString("MenuContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index.
        /// </summary>
        public static string MenuIndex {
            get {
                return ResourceManager.GetString("MenuIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert Group After.
        /// </summary>
        public static string MenuInsertGroupAfter {
            get {
                return ResourceManager.GetString("MenuInsertGroupAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Group.
        /// </summary>
        public static string MenuInsertGroupAsChild {
            get {
                return ResourceManager.GetString("MenuInsertGroupAsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert Group Before.
        /// </summary>
        public static string MenuInsertGroupBefore {
            get {
                return ResourceManager.GetString("MenuInsertGroupBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert Separator After.
        /// </summary>
        public static string MenuInsertSeparatorAfter {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Separator.
        /// </summary>
        public static string MenuInsertSeparatorAsChild {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorAsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert Separator Before.
        /// </summary>
        public static string MenuInsertSeparatorBefore {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preferences.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename.
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Tools.
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Utilities.
        /// </summary>
        public static string MenuUtilities {
            get {
                return ResourceManager.GetString("MenuUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The background task is still running.  Are you sure you want to cancel?.
        /// </summary>
        public static string MessageConfirmCancelTask {
            get {
                return ResourceManager.GetString("MessageConfirmCancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data has been modified and changes will be lost.  Discard changes and close?.
        /// </summary>
        public static string MessageConfirmDiscardChangesBeforeClosing {
            get {
                return ResourceManager.GetString("MessageConfirmDiscardChangesBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import settings meta-data defined in locally installed plugins?.
        /// </summary>
        public static string MessageConfirmImportSettingsMetaData {
            get {
                return ResourceManager.GetString("MessageConfirmImportSettingsMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application must restart in order to apply the new display language. Would you like to restart now?.
        /// </summary>
        public static string MessageDisplayLanguageChangedRestartRequired {
            get {
                return ResourceManager.GetString("MessageDisplayLanguageChangedRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No configuration pages exist..
        /// </summary>
        public static string MessageNoConfigurationPagesExist {
            get {
                return ResourceManager.GetString("MessageNoConfigurationPagesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This group contains one or more items. Items may not be deleted, but can be hidden..
        /// </summary>
        public static string MessageNodeNotEmpty {
            get {
                return ResourceManager.GetString("MessageNodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset this setting back to its default value?.
        /// </summary>
        public static string MessageReset {
            get {
                return ResourceManager.GetString("MessageReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset all settings back to default values?.
        /// </summary>
        public static string MessageResetAll {
            get {
                return ResourceManager.GetString("MessageResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings have been modified.  Save changes?.
        /// </summary>
        public static string MessageSaveModified {
            get {
                return ResourceManager.GetString("MessageSaveModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save the selected settings values.  Please ensure the values entered are properly formatted for the data type..
        /// </summary>
        public static string MessageSaveSettingFailed {
            get {
                return ResourceManager.GetString("MessageSaveSettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The settings store is currently offline.  Please try again later..
        /// </summary>
        public static string MessageSettingsStoreOffline {
            get {
                return ResourceManager.GetString("MessageSettingsStoreOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error has occurred which prevents the further use of this application. This application will now shut down to prevent damage to the system..
        /// </summary>
        public static string MessageUnexpectedErrorQuit {
            get {
                return ResourceManager.GetString("MessageUnexpectedErrorQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unrecognized format.
        /// </summary>
        public static string MessageUnrecognizedFormat {
            get {
                return ResourceManager.GetString("MessageUnrecognizedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updating your personal preferences ....
        /// </summary>
        public static string MessageUpdatingPreferences {
            get {
                return ResourceManager.GetString("MessageUpdatingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One or more errors have occurred while updating your preferences.  Some of your preferences may not have been properly configured..
        /// </summary>
        public static string MessageUserUpgradeFailures {
            get {
                return ResourceManager.GetString("MessageUserUpgradeFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value required.
        /// </summary>
        public static string MessageValueRequired {
            get {
                return ResourceManager.GetString("MessageValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alerts.
        /// </summary>
        public static string TitleAlertViewer {
            get {
                return ResourceManager.GetString("TitleAlertViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string TitleCancel {
            get {
                return ResourceManager.GetString("TitleCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string TitleClose {
            get {
                return ResourceManager.GetString("TitleClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close Assistant.
        /// </summary>
        public static string TitleCloseAssistant {
            get {
                return ResourceManager.GetString("TitleCloseAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date Format.
        /// </summary>
        public static string TitleDateFormat {
            get {
                return ResourceManager.GetString("TitleDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default Value.
        /// </summary>
        public static string TitleDefaultValue {
            get {
                return ResourceManager.GetString("TitleDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Value.
        /// </summary>
        public static string TitleEditValue {
            get {
                return ResourceManager.GetString("TitleEditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group.
        /// </summary>
        public static string TitleGroup {
            get {
                return ResourceManager.GetString("TitleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preferences.
        /// </summary>
        public static string TitleMenuOptions {
            get {
                return ResourceManager.GetString("TitleMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next Page.
        /// </summary>
        public static string TitleNext {
            get {
                return ResourceManager.GetString("TitleNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous Page.
        /// </summary>
        public static string TitlePrevious {
            get {
                return ResourceManager.GetString("TitlePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property.
        /// </summary>
        public static string TitleProperty {
            get {
                return ResourceManager.GetString("TitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename.
        /// </summary>
        public static string TitleRename {
            get {
                return ResourceManager.GetString("TitleRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scope.
        /// </summary>
        public static string TitleScope {
            get {
                return ResourceManager.GetString("TitleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings Editor.
        /// </summary>
        public static string TitleSettingsEditor {
            get {
                return ResourceManager.GetString("TitleSettingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toolbar.
        /// </summary>
        public static string TitleToolbar {
            get {
                return ResourceManager.GetString("TitleToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string TitleType {
            get {
                return ResourceManager.GetString("TitleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updating Preferences ....
        /// </summary>
        public static string TitleUpdatingPreferences {
            get {
                return ResourceManager.GetString("TitleUpdatingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string TitleValue {
            get {
                return ResourceManager.GetString("TitleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string TitleVersion {
            get {
                return ResourceManager.GetString("TitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Group.
        /// </summary>
        public static string ToolbarAddGroup {
            get {
                return ResourceManager.GetString("ToolbarAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Separator.
        /// </summary>
        public static string ToolbarAddSeparator {
            get {
                return ResourceManager.GetString("ToolbarAddSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string ToolbarRemove {
            get {
                return ResourceManager.GetString("ToolbarRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename.
        /// </summary>
        public static string ToolbarRename {
            get {
                return ResourceManager.GetString("ToolbarRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can configure this item, but you do not have permission to use it..
        /// </summary>
        public static string TooltipActionNotPermitted {
            get {
                return ResourceManager.GetString("TooltipActionNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}:
        ///You can configure this item, but you do not have permission to use it..
        /// </summary>
        public static string TooltipFormatActionNotPermitted {
            get {
                return ResourceManager.GetString("TooltipFormatActionNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import settings meta-data from local plugins.
        /// </summary>
        public static string TooltipImportSettingsMetaData {
            get {
                return ResourceManager.GetString("TooltipImportSettingsMetaData", resourceCulture);
            }
        }
    }
}
